# -*- coding: utf-8 -*-
"""rm code.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10KpgVG5JghS6FuCkyfTat5lmm_jRPh3-
"""

# =========================
# Import libraries
# =========================
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import glob

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.metrics import accuracy_score, f1_score, roc_auc_score, confusion_matrix, classification_report
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from xgboost import XGBClassifier
from sklearn.neural_network import MLPClassifier

# =========================
# 1. Load and combine dataset
# =========================
path = "/content/"
all_files = glob.glob(path + "/*.csv")

dfs = []
for file in all_files:
    df_temp = pd.read_csv(file)
    dfs.append(df_temp)

df = pd.concat(dfs, ignore_index=True)

# Convert datetime
if "Date (LT)" in df.columns:
    date_col = "Date (LT)"
    df[date_col] = pd.to_datetime(df[date_col], errors="coerce")
else:
    raise ValueError("No valid date column found")

# Ensure PM2.5 concentration column
df['NowCast Conc.'] = pd.to_numeric(df['NowCast Conc.'], errors='coerce')
df = df.dropna(subset=['NowCast Conc.', date_col])
df = df.sort_values(by=date_col).reset_index(drop=True)

# =========================
# 2. PM2.5 → AQI Category
# =========================
def pm25_to_aqi_category(pm25):
    if pm25 <= 50:
        return "Good"
    elif pm25 <= 100:
        return "Moderate"
    elif pm25 <= 150:
        return "Unhealthy for Sensitive"
    elif pm25 <= 200:
        return "Unhealthy"
    elif pm25 <= 300:
        return "Very Unhealthy"
    else:
        return "Hazardous"

df['AQI_Category'] = df['NowCast Conc.'].apply(pm25_to_aqi_category)

# =========================
# 3. Feature Engineering
# =========================
df['Year'] = df[date_col].dt.year
df['Month'] = df[date_col].dt.month
df['Day'] = df[date_col].dt.day
df['Weekday'] = df[date_col].dt.weekday
df['DayOfYear'] = df[date_col].dt.dayofyear

# Lag features (previous pollution levels)
for lag in [1, 2, 3, 7, 14]:
    df[f'PM_Lag_{lag}'] = df['NowCast Conc.'].shift(lag)

# Rolling mean features (smoothed pollution trends)
for window in [3, 7, 14]:
    df[f'PM_Roll_{window}'] = df['NowCast Conc.'].rolling(window=window).mean().shift(1)

# Drop rows with NaNs created by lags/rolling
df = df.dropna().reset_index(drop=True)

# =========================
# 4. Prepare X, y
# =========================
feature_cols = [
    'Year', 'Month', 'Day', 'Weekday', 'DayOfYear'
] + [f'PM_Lag_{lag}' for lag in [1,2,3,7,14]] + [f'PM_Roll_{w}' for w in [3,7,14]]

X = df[feature_cols]
y = df['AQI_Category']

# Encode target
le = LabelEncoder()
y = le.fit_transform(y)

# =========================
# 5. Split data (stratified)
# =========================
X_train, X_temp, y_train, y_temp = train_test_split(X, y, test_size=0.3, stratify=y, random_state=42)
X_val, X_test, y_val, y_test = train_test_split(X_temp, y_temp, test_size=0.5, stratify=y_temp, random_state=42)

# Scale features
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_val = scaler.transform(X_val)
X_test = scaler.transform(X_test)

# =========================
# 6. Define models
# =========================
models = {
    "Logistic Regression": LogisticRegression(max_iter=2000, class_weight="balanced"),
    "Random Forest": RandomForestClassifier(n_estimators=300, max_depth=20, random_state=42, class_weight="balanced"),
    "SVM": SVC(kernel='rbf', probability=True, class_weight="balanced", random_state=42),
    "XGBoost": XGBClassifier(learning_rate=0.05, max_depth=6, n_estimators=300, eval_metric='mlogloss', use_label_encoder=False, random_state=42),
    "MLP": MLPClassifier(hidden_layer_sizes=(200,100), max_iter=2000, early_stopping=True, random_state=42)
}

# =========================
# 7. Train & Evaluate
# =========================
results = []
reports = {}  # Store classification reports

for name, model in models.items():
    model.fit(X_train, y_train)
    y_pred = model.predict(X_val)
    y_proba = model.predict_proba(X_val) if hasattr(model, "predict_proba") else None

    acc = accuracy_score(y_val, y_pred)
    f1 = f1_score(y_val, y_pred, average="weighted")

    if y_proba is not None and y_proba.shape[1] > 1:
        roc = roc_auc_score(y_val, y_proba, multi_class="ovr")
    else:
        roc = None

    results.append([name, acc, f1, roc])

    # Save classification report as DataFrame
    report_dict = classification_report(y_val, y_pred, target_names=le.classes_, output_dict=True)
    reports[name] = pd.DataFrame(report_dict).transpose()

    print(f"\n=== {name} ===")
    print("Accuracy:", acc)
    print("F1 Score:", f1)
    print("ROC-AUC Score:", roc)
    print("Confusion Matrix:\n", confusion_matrix(y_val, y_pred))
    print(classification_report(y_val, y_pred, target_names=le.classes_))

# =========================
# 7c. Save Confusion Matrices Separately
# =========================
for name, model in models.items():
    y_pred = model.predict(X_val)
    cm = confusion_matrix(y_val, y_pred)

    plt.figure(figsize=(6, 5))
    sns.heatmap(cm, annot=True, fmt="d", cmap="Blues",
                xticklabels=le.classes_, yticklabels=le.classes_)
    plt.title(f"Confusion Matrix - {name}")
    plt.xlabel("Predicted")
    plt.ylabel("Actual")
    plt.savefig(f"confusion_matrix_{name.replace(' ', '_')}.png", dpi=300, bbox_inches="tight")
    plt.close()

# =========================
# 8. Model Comparison
# =========================
result_df = pd.DataFrame(results, columns=["Model", "Accuracy", "F1-Score", "ROC-AUC"]).sort_values(by="F1-Score", ascending=False)
print("\n\nModel Comparison (Validation Set):\n", result_df)

# =========================
# 9. Save Classification Reports as CSV
# =========================
for name, report_df in reports.items():
    report_df.to_csv(f"classification_report_{name.replace(' ', '_')}.csv")

print("\nClassification reports saved as CSV files.")

# =========================
# 10. Final Test Evaluation
# =========================
best_model_name = result_df.iloc[0, 0]
best_model = models[best_model_name]
y_test_pred = best_model.predict(X_test)
y_test_proba = best_model.predict_proba(X_test) if hasattr(best_model, "predict_proba") else None

print(f"\n=== Final Test Evaluation ({best_model_name}) ===")
print("Accuracy:", accuracy_score(y_test, y_test_pred))
print("F1 Score:", f1_score(y_test, y_test_pred, average='weighted'))
if y_test_proba is not None and y_test_proba.shape[1] > 1:
    print("ROC-AUC Score:", roc_auc_score(y_test, y_test_proba, multi_class="ovr"))
print("Confusion Matrix:\n", confusion_matrix(y_test, y_test_pred))
print(classification_report(y_test, y_test_pred, target_names=le.classes_))

# Import libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import glob

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.metrics import accuracy_score, f1_score, roc_auc_score, confusion_matrix, classification_report
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from xgboost import XGBClassifier
from sklearn.neural_network import MLPClassifier

# =========================
# 1. Load and combine dataset
# =========================
path = "/content/"
all_files = glob.glob(path + "/*.csv")

dfs = []
for file in all_files:
    df_temp = pd.read_csv(file)
    dfs.append(df_temp)

df = pd.concat(dfs, ignore_index=True)

# Convert datetime
if "Date (LT)" in df.columns:
    date_col = "Date (LT)"
    df[date_col] = pd.to_datetime(df[date_col], errors="coerce")
else:
    raise ValueError("No valid date column found")

# Ensure PM2.5 concentration column
df['NowCast Conc.'] = pd.to_numeric(df['NowCast Conc.'], errors='coerce')
df = df.dropna(subset=['NowCast Conc.', date_col])
df = df.sort_values(by=date_col).reset_index(drop=True)

# =========================
# 2. PM2.5 → AQI Category
# =========================
def pm25_to_aqi_category(pm25):
    if pm25 <= 50:
        return "Good"
    elif pm25 <= 100:
        return "Moderate"
    elif pm25 <= 150:
        return "Unhealthy for Sensitive"
    elif pm25 <= 200:
        return "Unhealthy"
    elif pm25 <= 300:
        return "Very Unhealthy"
    else:
        return "Hazardous"

df['AQI_Category'] = df['NowCast Conc.'].apply(pm25_to_aqi_category)

# =========================
# 3. Feature Engineering
# =========================
df['Year'] = df[date_col].dt.year
df['Month'] = df[date_col].dt.month
df['Day'] = df[date_col].dt.day
df['Weekday'] = df[date_col].dt.weekday
df['DayOfYear'] = df[date_col].dt.dayofyear

# Lag features (previous pollution levels)
for lag in [1, 2, 3, 7, 14]:
    df[f'PM_Lag_{lag}'] = df['NowCast Conc.'].shift(lag)

# Rolling mean features (smoothed pollution trends)
for window in [3, 7, 14]:
    df[f'PM_Roll_{window}'] = df['NowCast Conc.'].rolling(window=window).mean().shift(1)

# Drop rows with NaNs created by lags/rolling
df = df.dropna().reset_index(drop=True)

# =========================
# 4. Prepare X, y
# =========================
feature_cols = [
    'Year', 'Month', 'Day', 'Weekday', 'DayOfYear'
] + [f'PM_Lag_{lag}' for lag in [1,2,3,7,14]] + [f'PM_Roll_{w}' for w in [3,7,14]]

X = df[feature_cols]
y = df['AQI_Category']

# Encode target
le = LabelEncoder()
y = le.fit_transform(y)

# =========================
# 5. Split data (stratified)
# =========================
X_train, X_temp, y_train, y_temp = train_test_split(X, y, test_size=0.3, stratify=y, random_state=42)
X_val, X_test, y_val, y_test = train_test_split(X_temp, y_temp, test_size=0.5, stratify=y_temp, random_state=42)

# Scale features
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_val = scaler.transform(X_val)
X_test = scaler.transform(X_test)

# =========================
# 6. Define models
# =========================
models = {
    "Logistic Regression": LogisticRegression(max_iter=2000, class_weight="balanced"),
    "Random Forest": RandomForestClassifier(n_estimators=300, max_depth=20, random_state=42, class_weight="balanced"),
    "SVM": SVC(kernel='rbf', probability=True, class_weight="balanced", random_state=42),
    "XGBoost": XGBClassifier(learning_rate=0.05, max_depth=6, n_estimators=300, eval_metric='mlogloss', use_label_encoder=False, random_state=42),
    "MLP": MLPClassifier(hidden_layer_sizes=(200,100), max_iter=2000, early_stopping=True, random_state=42)
}

# =========================
# 7. Train & Evaluate
# =========================
results = []
for name, model in models.items():
    model.fit(X_train, y_train)
    y_pred = model.predict(X_val)
    y_proba = model.predict_proba(X_val) if hasattr(model, "predict_proba") else None

    acc = accuracy_score(y_val, y_pred)
    f1 = f1_score(y_val, y_pred, average="weighted")

    if y_proba is not None and y_proba.shape[1] > 1:
        roc = roc_auc_score(y_val, y_proba, multi_class="ovr")
    else:
        roc = None

    results.append([name, acc, f1, roc])

    print(f"\n=== {name} ===")
    print("Accuracy:", acc)
    print("F1 Score:", f1)
    print("ROC-AUC Score:", roc)
    print("Confusion Matrix:\n", confusion_matrix(y_val, y_pred))
    print(classification_report(y_val, y_pred, target_names=le.classes_))

# =========================
# 8. Model Comparison
# =========================
result_df = pd.DataFrame(results, columns=["Model", "Accuracy", "F1-Score", "ROC-AUC"]).sort_values(by="F1-Score", ascending=False)
print("\n\nModel Comparison (Validation Set):\n", result_df)

# =========================
# 9. Final Test Evaluation
# =========================
best_model_name = result_df.iloc[0, 0]
best_model = models[best_model_name]
y_test_pred = best_model.predict(X_test)
y_test_proba = best_model.predict_proba(X_test) if hasattr(best_model, "predict_proba") else None

print(f"\n=== Final Test Evaluation ({best_model_name}) ===")
print("Accuracy:", accuracy_score(y_test, y_test_pred))
print("F1 Score:", f1_score(y_test, y_test_pred, average='weighted'))
if y_test_proba is not None and y_test_proba.shape[1] > 1:
    print("ROC-AUC Score:", roc_auc_score(y_test, y_test_proba, multi_class="ovr"))
print("Confusion Matrix:\n", confusion_matrix(y_test, y_test_pred))
print(classification_report(y_test, y_test_pred, target_names=le.classes_))

# =========================
# Import libraries
# =========================
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import glob

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.metrics import accuracy_score, f1_score, roc_auc_score, confusion_matrix, classification_report
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from xgboost import XGBClassifier
from sklearn.neural_network import MLPClassifier

# =========================
# 1. Load and combine dataset
# =========================
path = "/content/"
all_files = glob.glob(path + "/*.csv")

dfs = []
for file in all_files:
    df_temp = pd.read_csv(file)
    dfs.append(df_temp)

df = pd.concat(dfs, ignore_index=True)

# Convert datetime
if "Date (LT)" in df.columns:
    date_col = "Date (LT)"
    df[date_col] = pd.to_datetime(df[date_col], errors="coerce")
else:
    raise ValueError("No valid date column found")

# Ensure PM2.5 concentration column
df['NowCast Conc.'] = pd.to_numeric(df['NowCast Conc.'], errors='coerce')
df = df.dropna(subset=['NowCast Conc.', date_col])
df = df.sort_values(by=date_col).reset_index(drop=True)

# =========================
# 2. PM2.5 → AQI Category
# =========================
def pm25_to_aqi_category(pm25):
    if pm25 <= 50:
        return "Good"
    elif pm25 <= 100:
        return "Moderate"
    elif pm25 <= 150:
        return "Unhealthy for Sensitive"
    elif pm25 <= 200:
        return "Unhealthy"
    elif pm25 <= 300:
        return "Very Unhealthy"
    else:
        return "Hazardous"

df['AQI_Category'] = df['NowCast Conc.'].apply(pm25_to_aqi_category)

# =========================
# 3. Feature Engineering
# =========================
df['Year'] = df[date_col].dt.year
df['Month'] = df[date_col].dt.month
df['Day'] = df[date_col].dt.day
df['Weekday'] = df[date_col].dt.weekday
df['DayOfYear'] = df[date_col].dt.dayofyear

# Lag features (previous pollution levels)
for lag in [1, 2, 3, 7, 14]:
    df[f'PM_Lag_{lag}'] = df['NowCast Conc.'].shift(lag)

# Rolling mean features (smoothed pollution trends)
for window in [3, 7, 14]:
    df[f'PM_Roll_{window}'] = df['NowCast Conc.'].rolling(window=window).mean().shift(1)

# Drop rows with NaNs created by lags/rolling
df = df.dropna().reset_index(drop=True)

# =========================
# 4. Prepare X, y
# =========================
feature_cols = [
    'Year', 'Month', 'Day', 'Weekday', 'DayOfYear'
] + [f'PM_Lag_{lag}' for lag in [1,2,3,7,14]] + [f'PM_Roll_{w}' for w in [3,7,14]]

X = df[feature_cols]
y = df['AQI_Category']

# Encode target
le = LabelEncoder()
y = le.fit_transform(y)

# =========================
# 5. Split data (stratified)
# =========================
X_train, X_temp, y_train, y_temp = train_test_split(X, y, test_size=0.3, stratify=y, random_state=42)
X_val, X_test, y_val, y_test = train_test_split(X_temp, y_temp, test_size=0.5, stratify=y_temp, random_state=42)

# Scale features
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_val = scaler.transform(X_val)
X_test = scaler.transform(X_test)

# =========================
# 6. Define models
# =========================
models = {
    "Logistic Regression": LogisticRegression(max_iter=2000, class_weight="balanced"),
    "Random Forest": RandomForestClassifier(n_estimators=300, max_depth=20, random_state=42, class_weight="balanced"),
    "SVM": SVC(kernel='rbf', probability=True, class_weight="balanced", random_state=42),
    "XGBoost": XGBClassifier(learning_rate=0.05, max_depth=6, n_estimators=300, eval_metric='mlogloss', use_label_encoder=False, random_state=42),
    "MLP": MLPClassifier(hidden_layer_sizes=(200,100), max_iter=2000, early_stopping=True, random_state=42)
}

# =========================
# 7. Train & Evaluate
# =========================
results = []
for name, model in models.items():
    model.fit(X_train, y_train)
    y_pred = model.predict(X_val)
    y_proba = model.predict_proba(X_val) if hasattr(model, "predict_proba") else None

    acc = accuracy_score(y_val, y_pred)
    f1 = f1_score(y_val, y_pred, average="weighted")

    if y_proba is not None and y_proba.shape[1] > 1:
        roc = roc_auc_score(y_val, y_proba, multi_class="ovr")
    else:
        roc = None

    results.append([name, acc, f1, roc])

    print(f"\n=== {name} ===")
    print("Accuracy:", acc)
    print("F1 Score:", f1)
    print("ROC-AUC Score:", roc)
    print("Confusion Matrix:\n", confusion_matrix(y_val, y_pred))
    print(classification_report(y_val, y_pred, target_names=le.classes_))

# =========================
# 7c. Save Confusion Matrices Separately
# =========================
for name, model in models.items():
    y_pred = model.predict(X_val)
    cm = confusion_matrix(y_val, y_pred)

    plt.figure(figsize=(6, 5))
    sns.heatmap(cm, annot=True, fmt="d", cmap="Blues",
                xticklabels=le.classes_, yticklabels=le.classes_)
    plt.title(f"Confusion Matrix - {name}")
    plt.xlabel("Predicted")
    plt.ylabel("Actual")
    plt.savefig(f"confusion_matrix_{name.replace(' ', '_')}.png", dpi=300, bbox_inches="tight")
    plt.close()

# =========================
# 8. Model Comparison
# =========================
result_df = pd.DataFrame(results, columns=["Model", "Accuracy", "F1-Score", "ROC-AUC"]).sort_values(by="F1-Score", ascending=False)
print("\n\nModel Comparison (Validation Set):\n", result_df)

# =========================
# 9. Final Test Evaluation
# =========================
best_model_name = result_df.iloc[0, 0]
best_model = models[best_model_name]
y_test_pred = best_model.predict(X_test)
y_test_proba = best_model.predict_proba(X_test) if hasattr(best_model, "predict_proba") else None

print(f"\n=== Final Test Evaluation ({best_model_name}) ===")
print("Accuracy:", accuracy_score(y_test, y_test_pred))
print("F1 Score:", f1_score(y_test, y_test_pred, average='weighted'))
if y_test_proba is not None and y_test_proba.shape[1] > 1:
    print("ROC-AUC Score:", roc_auc_score(y_test, y_test_proba, multi_class="ovr"))
print("Confusion Matrix:\n", confusion_matrix(y_test, y_test_pred))
print(classification_report(y_test, y_test_pred, target_names=le.classes_))



# Import libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import glob

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.metrics import accuracy_score, f1_score, roc_auc_score, confusion_matrix, classification_report
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier, VotingClassifier
from sklearn.svm import SVC
from xgboost import XGBClassifier
from lightgbm import LGBMClassifier
from catboost import CatBoostClassifier
from sklearn.neural_network import MLPClassifier

# =========================
# 1. Load dataset
# =========================
path = "/content/"
all_files = glob.glob(path + "/*.csv")

dfs = []
for file in all_files:
    df_temp = pd.read_csv(file)
    dfs.append(df_temp)

df = pd.concat(dfs, ignore_index=True)

# Convert datetime
date_col = "Date (LT)"
df[date_col] = pd.to_datetime(df[date_col], errors="coerce")

# Ensure PM2.5 concentration column
df['NowCast Conc.'] = pd.to_numeric(df['NowCast Conc.'], errors='coerce')
df = df.dropna(subset=['NowCast Conc.', date_col])
df = df.sort_values(by=date_col).reset_index(drop=True)

# =========================
# 2. PM2.5 → AQI Category
# =========================
def pm25_to_aqi_category(pm25):
    if pm25 <= 50:
        return "Good"
    elif pm25 <= 100:
        return "Moderate"
    elif pm25 <= 150:
        return "Unhealthy for Sensitive"
    elif pm25 <= 200:
        return "Unhealthy"
    elif pm25 <= 300:
        return "Very Unhealthy"
    else:
        return "Hazardous"

df['AQI_Category'] = df['NowCast Conc.'].apply(pm25_to_aqi_category)

# =========================
# 3. Feature Engineering
# =========================
df['Year'] = df[date_col].dt.year
df['Month'] = df[date_col].dt.month
df['Day'] = df[date_col].dt.day
df['Weekday'] = df[date_col].dt.weekday
df['DayOfYear'] = df[date_col].dt.dayofyear

# Lag features
for lag in [1, 2, 3, 7, 14]:
    df[f'PM_Lag_{lag}'] = df['NowCast Conc.'].shift(lag)

# Rolling mean features
for window in [3, 7, 14]:
    df[f'PM_Roll_{window}'] = df['NowCast Conc.'].rolling(window=window).mean().shift(1)

# Drop NaNs from lag/rolling
df = df.dropna().reset_index(drop=True)

# =========================
# 4. Prepare X, y
# =========================
feature_cols = [
    'Year', 'Month', 'Day', 'Weekday', 'DayOfYear'
] + [f'PM_Lag_{lag}' for lag in [1,2,3,7,14]] + [f'PM_Roll_{w}' for w in [3,7,14]]

X = df[feature_cols]
y = df['AQI_Category']

# Encode target
le = LabelEncoder()
y = le.fit_transform(y)

# =========================
# 5. Split data
# =========================
X_train, X_temp, y_train, y_temp = train_test_split(X, y, test_size=0.3, stratify=y, random_state=42)
X_val, X_test, y_val, y_test = train_test_split(X_temp, y_temp, test_size=0.5, stratify=y_temp, random_state=42)

# Scale features
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_val = scaler.transform(X_val)
X_test = scaler.transform(X_test)

# =========================
# 6. Define Models
# =========================
models = {
    "Logistic Regression": LogisticRegression(max_iter=2000, class_weight="balanced"),
    "Random Forest": RandomForestClassifier(n_estimators=400, max_depth=25, random_state=42, class_weight="balanced"),
    "SVM": SVC(kernel='rbf', probability=True, class_weight="balanced", random_state=42),
    "XGBoost": XGBClassifier(learning_rate=0.05, max_depth=8, n_estimators=400, subsample=0.8,
                              colsample_bytree=0.8, eval_metric='mlogloss', random_state=42),
    "LightGBM": LGBMClassifier(n_estimators=400, learning_rate=0.05, max_depth=-1, random_state=42, class_weight="balanced"),
    "CatBoost": CatBoostClassifier(iterations=400, learning_rate=0.05, depth=8, verbose=0, random_state=42),
    "MLP": MLPClassifier(hidden_layer_sizes=(256,128), max_iter=2000, alpha=0.001, early_stopping=True, random_state=42)
}

# =========================
# 7. Train & Evaluate + Confusion Matrices
# =========================
results = []
fig, axes = plt.subplots(3, 3, figsize=(18, 15))
axes = axes.ravel()

for i, (name, model) in enumerate(models.items()):
    model.fit(X_train, y_train)
    y_pred = model.predict(X_val)
    y_proba = model.predict_proba(X_val) if hasattr(model, "predict_proba") else None

    acc = accuracy_score(y_val, y_pred)
    f1 = f1_score(y_val, y_pred, average="weighted")
    roc = roc_auc_score(y_val, y_proba, multi_class="ovr") if y_proba is not None else None

    results.append([name, acc, f1, roc])

    # Confusion Matrix
    cm = confusion_matrix(y_val, y_pred)
    sns.heatmap(cm, annot=True, fmt="d", cmap="Blues",
                xticklabels=le.classes_, yticklabels=le.classes_, ax=axes[i])
    axes[i].set_title(f"{name}\nAcc={acc:.2f}, F1={f1:.2f}")
    axes[i].set_xlabel("Predicted")
    axes[i].set_ylabel("Actual")

plt.tight_layout()
plt.show()

# =========================
# 8. Results Summary
# =========================
result_df = pd.DataFrame(results, columns=["Model", "Accuracy", "F1-Score", "ROC-AUC"]).sort_values(by="F1-Score", ascending=False)
print("\n\nModel Comparison (Validation Set):\n", result_df)

# =========================
# 9. Final Test Evaluation on Best Model
# =========================
best_model_name = result_df.iloc[0, 0]
best_model = models[best_model_name]
y_test_pred = best_model.predict(X_test)
y_test_proba = best_model.predict_proba(X_test) if hasattr(best_model, "predict_proba") else None

print(f"\n=== Final Test Evaluation ({best_model_name}) ===")
print("Accuracy:", accuracy_score(y_test, y_test_pred))
print("F1 Score:", f1_score(y_test, y_test_pred, average='weighted'))
if y_test_proba is not None and y_test_proba.shape[1] > 1:
    print("ROC-AUC Score:", roc_auc_score(y_test, y_test_proba, multi_class="ovr"))
print("Confusion Matrix:\n", confusion_matrix(y_test, y_test_pred))
print(classification_report(y_test, y_test_pred, target_names=le.classes_))

!pip install catboost

"""After the installation is complete, please run the code cell again."""